// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetEnterprise.Infrastruture.Persistence;

#nullable disable

namespace NetEnterprise.Infrastruture.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209210935_PrimerEntidades")]
    partial class PrimerEntidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Catalog.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GroupId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<int>("CreateUser")
                        .HasColumnType("int")
                        .HasColumnName("CreateUser");

                    b.Property<DateTime>("DateCreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateUpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("int")
                        .HasColumnName("UpdateUser");

                    b.HasKey("GroupId");

                    b.HasIndex("BranchId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Group_Name");

                    b.ToTable("Groups", "Catalog");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Catalog.SubGroup", b =>
                {
                    b.Property<int>("SubGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubGroupId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubGroupId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<int>("CreateUser")
                        .HasColumnType("int")
                        .HasColumnName("CreateUser");

                    b.Property<DateTime>("DateCreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateUpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("int")
                        .HasColumnName("UpdateUser");

                    b.HasKey("SubGroupId");

                    b.HasIndex("BranchId");

                    b.HasIndex("GroupId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Group_Name");

                    b.ToTable("SubGroups", "Catalog");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Global.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CountryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CountryCode");

                    b.Property<int>("CreateUser")
                        .HasColumnType("int")
                        .HasColumnName("CreateUser");

                    b.Property<DateTime>("DateCreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateUpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Description")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("LanguageId");

                    b.Property<int?>("UTCdiff")
                        .HasColumnType("int")
                        .HasColumnName("UTCdiff");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("int")
                        .HasColumnName("UpdateUser");

                    b.HasKey("CountryId");

                    b.HasIndex("CountryCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Country_CountryCode");

                    b.ToTable("Country", "Global");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Global.IndustryType", b =>
                {
                    b.Property<int>("IndustryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IndustryTypeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndustryTypeId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<int>("CreateUser")
                        .HasColumnType("int")
                        .HasColumnName("CreateUser");

                    b.Property<DateTime>("DateCreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateUpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.Property<string>("IndustryCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("IndustryCode");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("int")
                        .HasColumnName("UpdateUser");

                    b.HasKey("IndustryTypeId");

                    b.ToTable("IndustryTypes", "Global");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Management.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasDefaultValue("")
                        .HasColumnName("AddressCity");

                    b.Property<string>("AddressCountry")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasDefaultValue("México")
                        .HasColumnName("AddressCountry");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("AddressLine2");

                    b.Property<string>("AddressMunicipality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasDefaultValue("")
                        .HasColumnName("AddressMunicipality");

                    b.Property<string>("AddressPostalCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("")
                        .HasColumnName("AddressPostalCode");

                    b.Property<string>("AddressState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasDefaultValue("")
                        .HasColumnName("AddressState");

                    b.Property<string>("AddressSuburb")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasDefaultValue("")
                        .HasColumnName("AddressSuburb");

                    b.Property<int?>("BranchTypeId")
                        .HasColumnType("int")
                        .HasColumnName("BranchTypeId");

                    b.Property<Guid>("BranchUid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BranchUid");

                    b.Property<string>("CommercialName")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("CommercialName");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyId");

                    b.Property<int>("CreateUser")
                        .HasColumnType("int")
                        .HasColumnName("CreateUser");

                    b.Property<DateTime>("DateCreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateUpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasDefaultValue("")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasDefaultValue("")
                        .HasColumnName("Name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("SecondaryPhoneNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SecondaryPhoneNumber");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("")
                        .HasColumnName("TaxIdentificationNumber");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("int")
                        .HasColumnName("UpdateUser");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Website");

                    b.HasKey("BranchId");

                    b.HasIndex("BranchUid")
                        .IsUnique()
                        .HasDatabaseName("IX_Branches_BranchUid");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_Branches_CompanyId");

                    b.ToTable("Branches", "Management");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Management.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompanyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("BusinessName");

                    b.Property<string>("CompanyTitle")
                        .HasMaxLength(280)
                        .IsUnicode(false)
                        .HasColumnType("varchar(280)")
                        .HasColumnName("CompanyTitle");

                    b.Property<Guid>("CompanyUid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyUid");

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Country");

                    b.Property<int>("CreateUser")
                        .HasColumnType("int")
                        .HasColumnName("CreateUser");

                    b.Property<DateTime>("DateCreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateUpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ErpSystemCode")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("ErpSystemCode");

                    b.Property<string>("ExteriorNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ExteriorNumber");

                    b.Property<int?>("IndustryTypeId")
                        .HasColumnType("int")
                        .HasColumnName("IndustryTypeId");

                    b.Property<string>("InteriorNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("InteriorNumber");

                    b.Property<int?>("LegacyRecordId")
                        .HasColumnType("int")
                        .HasColumnName("LegacyRecordId");

                    b.Property<string>("Locality")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Locality");

                    b.Property<string>("Municipality")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Municipality");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Neighborhood");

                    b.Property<string>("PrimaryPhone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("PrimaryPhone");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SecondaryPhone");

                    b.Property<string>("State")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("State");

                    b.Property<string>("Street")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Street");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TaxId");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("int")
                        .HasColumnName("UpdateUser");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ZipCode");

                    b.HasKey("CompanyId");

                    b.HasIndex("BusinessName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Companies_BusinessName");

                    b.HasIndex("CompanyUid")
                        .IsUnique()
                        .HasDatabaseName("IX_Companies_CompanyUid");

                    b.HasIndex("IndustryTypeId");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Companies_TaxId");

                    b.ToTable("Companies", "Management");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Security.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<int>("CreateUser")
                        .HasColumnType("int")
                        .HasColumnName("CreateUser");

                    b.Property<DateTime>("DateCreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateUpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Description")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RoleCode");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("int")
                        .HasColumnName("UpdateUser");

                    b.HasKey("RoleId");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoleCode")
                        .IsUnique()
                        .HasDatabaseName("IX_RoleCode");

                    b.ToTable("Role", "Security");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Security.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("AcceptanceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("AcceptanceDate");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<DateTime?>("BlockedToDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("BlockedToDate");

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<bool>("ChangePasswordRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ChangePasswordRequest");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryId");

                    b.Property<int>("CreateUser")
                        .HasColumnType("int")
                        .HasColumnName("CreateUser");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("DateCreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateUpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdatedTime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2")
                        .HasColumnName("Expiration");

                    b.Property<int?>("IncorrectPasswordAttempts")
                        .HasColumnType("int")
                        .HasColumnName("IncorrectPasswordAttempts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Password")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Password")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<Guid?>("PasswordRecoveryToken")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PasswordRecoveryToken");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PhoneNumber");

                    b.Property<bool>("PrivacyAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("PrivacyAccepted");

                    b.Property<int?>("PrivacyPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("PrivacyPolicyId");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RefreshToken");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.Property<int?>("UpdateUser")
                        .HasColumnType("int")
                        .HasColumnName("UpdateUser");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UserAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UserAccount")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("UserId");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_User_BranchId");

                    b.HasIndex("CountryId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserAccount")
                        .IsUnique()
                        .HasDatabaseName("IX_User_UserAccount");

                    b.ToTable("User", "Security");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Catalog.Group", b =>
                {
                    b.HasOne("NetEnterprise.Domain.Entities.Management.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Group_Branch");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Catalog.SubGroup", b =>
                {
                    b.HasOne("NetEnterprise.Domain.Entities.Management.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SubGroups_Branch");

                    b.HasOne("NetEnterprise.Domain.Entities.Catalog.Group", "Group")
                        .WithMany("SubGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SubGroups_Groups_GroupId");

                    b.Navigation("Branch");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Management.Branch", b =>
                {
                    b.HasOne("NetEnterprise.Domain.Entities.Management.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Branches_Companies");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Management.Company", b =>
                {
                    b.HasOne("NetEnterprise.Domain.Entities.Global.IndustryType", "IndustryType")
                        .WithMany()
                        .HasForeignKey("IndustryTypeId");

                    b.Navigation("IndustryType");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Security.Role", b =>
                {
                    b.HasOne("NetEnterprise.Domain.Entities.Management.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Role_Branch");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Security.User", b =>
                {
                    b.HasOne("NetEnterprise.Domain.Entities.Management.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User_Branch");

                    b.HasOne("NetEnterprise.Domain.Entities.Global.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetEnterprise.Domain.Entities.Security.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Branch");

                    b.Navigation("Country");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Catalog.Group", b =>
                {
                    b.Navigation("SubGroups");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Management.Company", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("NetEnterprise.Domain.Entities.Security.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
